### ISSUE TITLE
StreamCorruptedException: invalid type code on Java 11 and 12

### ISSUE THREAD

**Issue by dalelotts** [jsampson/prevayler#21]
I have a very old project using prevayler 2.6. Everything works on Java 8. 

Updating to Java 11 and reading previous snapshots throws StreamCorruptedException: invalid type code (the actual code changes). So far this only happens with one class BaseUser - a super class of the actual class being deserialized - SiteUser. 

Data types of the fields are List<Group>,  String, and byte[]  - Group data types are String and List<User>

I have not seen this error before and don't have experience debugging serialization (I didn't write this project) so any tips on where to start would be greatly appreciated.

```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.StreamCorruptedException: invalid type code: 86
	at net.firelord.phoenix.server.Server.start(Server.java:148)
	at org.tanukisoftware.wrapper.WrapperManager$11.run(WrapperManager.java:4146)
Caused by: java.lang.RuntimeException: java.io.StreamCorruptedException: invalid type code: 86
	at net.firelord.phoenix.servlet.Hosted.contextInitialized(Hosted.java:94)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:959)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:924)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at net.firelord.phoenix.server.Server.start(Server.java:143)
	... 1 common frames omitted
Caused by: java.io.StreamCorruptedException: invalid type code: 86
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1622)
	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:1968)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1588)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:566)
	at net.firelord.user.BaseUser.readObject(BaseUser.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2534)
	at java.base/java.io.ObjectInputStream.readFields(ObjectInputStream.java:610)
	at net.firelord.phoenix.component.ComponentImpl.readObject(ComponentImpl.java:604)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:566)
	at net.firelord.persistence.ObjectStore.readObject(ObjectStore.java:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at net.firelord.phoenix.core.persistence.ContainerAwareSerializer.readObject(ContainerAwareSerializer.java:55)
	at org.prevayler.implementation.snapshot.GenericSnapshotManager.readSnapshot(GenericSnapshotManager.java:100)
	at org.prevayler.implementation.snapshot.GenericSnapshotManager.<init>(GenericSnapshotManager.java:43)
	at org.prevayler.PrevaylerFactory.snapshotManager(PrevaylerFactory.java:364)
	at org.prevayler.PrevaylerFactory.create(PrevaylerFactory.java:316)
	at net.firelord.phoenix.servlet.Hosted.initializeSystem(Hosted.java:222)
	at net.firelord.phoenix.servlet.Hosted.prepare(Hosted.java:285)
	at net.firelord.phoenix.servlet.Hosted.contextInitialized(Hosted.java:90)
	... 18 common frames omitted
```

**Comment by karlwettin** [comment]
Can you paste in the complete stacktrace and error message?

**Comment by dalelotts** [comment]
@karlwettin added to the original post. The actual code reported varies depending on which snapshot is being loaded which leads me to believe it might be related to encoding but I don't see any encoding changes between 8 and 11. ¯\_(ツ)_/¯

**Comment by karlwettin** [comment]
I can’t till you what the problem is, but one way to find out might be to implement your own deserialization (implement Externalizable in BaseUser and SiteUser) that mimics the Java default behaviour and then set a breakpoint to figure out exactly what value causes the exception.

At least that would be a starting point with that would hint at something. 

Which Java 8 and Java 11 are you using? OpenJDK? Oracle? Other?

**Comment by dalelotts** [comment]
I'll give Externalizable a try. 
8 = OpenJDK
11 = Tried both Oracle 11.0.1 and OpenJDK 11.0.2 to see if there was a difference
Thanks!

**Comment by dalelotts** [comment]
@karlwettin It doesn't look like that it's allowed to change the serialization model of the class. 
It seems that an error is throw if the original saved class was not `Externalizable`

```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.InvalidClassException: net.firelord.user.BaseUser; Serializable incompatible with Externalizable
	at net.firelord.phoenix.server.Server.start(Server.java:148)
	at org.tanukisoftware.wrapper.WrapperManager$11.run(WrapperManager.java:4146)
Caused by: java.lang.RuntimeException: java.io.InvalidClassException: net.firelord.user.BaseUser; Serializable incompatible with Externalizable
	at net.firelord.phoenix.servlet.Hosted.contextInitialized(Hosted.java:94)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:959)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:924)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at net.firelord.phoenix.server.Server.start(Server.java:143)
	... 1 common frames omitted
Caused by: java.io.InvalidClassException: net.firelord.user.BaseUser; Serializable incompatible with Externalizable
	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:701)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2534)
	at java.base/java.io.ObjectInputStream.readFields(ObjectInputStream.java:610)
	at net.firelord.phoenix.component.ComponentImpl.readObject(ComponentImpl.java:604)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:566)
	at net.firelord.persistence.ObjectStore.readObject(ObjectStore.java:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at net.firelord.phoenix.core.persistence.ContainerAwareSerializer.readObject(ContainerAwareSerializer.java:55)
	at org.prevayler.implementation.snapshot.GenericSnapshotManager.readSnapshot(GenericSnapshotManager.java:100)
	at org.prevayler.implementation.snapshot.GenericSnapshotManager.<init>(GenericSnapshotManager.java:43)
	at org.prevayler.PrevaylerFactory.snapshotManager(PrevaylerFactory.java:364)
	at org.prevayler.PrevaylerFactory.create(PrevaylerFactory.java:316)
	at net.firelord.phoenix.servlet.Hosted.initializeSystem(Hosted.java:222)
	at net.firelord.phoenix.servlet.Hosted.prepare(Hosted.java:285)
	at net.firelord.phoenix.servlet.Hosted.contextInitialized(Hosted.java:90)
```

**Comment by jsampson** [comment]
Hi Dale,

Thanks for posting your issue! Here are a few quick thoughts.

Prevayler 2.6 was our more recent release, and was built against Java 6. We are currently planning to do a 2.7 release this summer, officially built against Java 8; and then a 3.0 release built against Java 11 at some future date. With that in mind, it might be safest for you to stick with Java 8 since that's currently working for you.

However, it does sound like your problem is with Java serialization rather than with Prevayler itself. Snapshots are written rather trivially -- open a FileOutputStream, wrap it in an ObjectOutputStream, call writeObject exactly once, then close the streams -- and are read just as trivially, so there shouldn't be anything about what Prevayler is doing that could cause stream corruption.

I did a bit of searching and it looks like most people who see StreamCorruptedException are writing multiple object streams to a single underlying stream, which we're not doing.

When you run against Java 11/12, are you compiling the code again, or are you running the existing code, compiled under Java 8 or earlier, against a Java 11/12 JVM? I'm wondering if recompiling the code could be causing some change in serialization format.

Do the classes in question have serialVersionUID fields declared? If not, that could also cause some problems with deserialization after recompiling, though I'm pretty sure it would be a different exception.

Building on Karl's debugging suggestion, perhaps you could leave the code alone and simply set a breakpoint in `BaseUser.readObject()` before the line where the exception is being thrown, and then step into the Java serialization code to see if it provides any clue as to the specific problem. The exception message is hinting at something about a field with an array type.

As a final radical thought, if you really have to get the app running on a Java 11/12 JVM, you could try bringing it up in the highest-version JVM that is able to load the snapshot successfully (e.g. a recent patch version of OpenJDK 8 or 9), and then trigger a _new_ snapshot to be written, and try loading that newly written snapshot in OpenJDK 11 or 12. It's possible that some serialization bugs were fixed in more recent JDKs. (Of course I presume that you have safely stored a backup of all the original snapshot and journal files that you're working with, so that writing a new snapshot is not overwriting your only copy!)

Cheers,
Justin

**Comment by dalelotts** [comment]
@jsampson thanks for the info.

I've taken both approaches - recompiling and not recompiling.

Yes, the classes have a `serialVersionUID`  

> I did a bit of searching and it looks like most people who see StreamCorruptedException are writing multiple object streams to a single underlying stream, which we're not doing.
I found the same results. I cannot find (at least yet) where we are opening more than object streams to a single underlying stream.

I've stepped into the deserialization code and it fails on on unknown `type code` - i.e. it does not know the data type being deserialized. There's not much for me to go on... I guess looking at the raw data and finding out how the encoding or structure might be changing ... feels big at this point.  `¯\_(ツ)_/¯`

Interesting enough, now that I look, BaseUser has a `readObject` method but does not have a `writeObject` method.  I didn't write this code but that seems super strange...

From  `BaseUser` - again, no `writeObject` method - it does have a 
```java
    private void readObject(final ObjectInputStream stream) throws ClassNotFoundException, IOException {

        stream.defaultReadObject();
        if (name == null) {
            throw new IllegalStateException("Null: name");
        }

        stream.registerValidation(new InputValidation(), 0);
    }
```

I think BaseUser should really be an abstract class but I'm a bit reluctant to make that change until I get this issue resolved.

I'll keep digging and update this issue as I learn more.

**Comment by karlwettin** [comment]
One alternative that bypass the problem is that you export your root using some alternative serialization (JSON?) on JDK8 and then import that root as an initial transaction on JDK11. You’ll of course lose all old events, so if you need to track back in time this would be a bit of a problem.

Btw, did you try to delete all snapshots and run only the journals from begining of time on JDK11?

**Comment by dalelotts** [comment]
Update: The data type of the field causing the error is a `byte[]`.   Java is not able to resolve the class from the class name `[B` in Java 11 but it works fine in Java 8. I now suspect something related to modules and/or the classpath.

Probably not related but interesting...I noticed that running the Prevayler tests on Java 11 or 12 the `DeepCopiertest.testParallelPathological` fails on `assertNotSame` because the newer Java primitive wrappers have a cache and return the same instance for all `Byte`'s of the same value.

**Comment by dalelotts** [comment]
allowArraySyntax is not supported - https://bugs.openjdk.java.net/browse/JDK-8175391 - so I `think` need to change my custom class loaders similar to use Class.forName(name, false)

**Comment by dalelotts** [comment]
Yep, that fixed it! Thanks for all of the suggestions, tips, and support!   It is unfortunate that such a simple change reports such a completely misleading error. The stream was not corrupt at all, everything was fine, it just wasn't able to resolve one of the persisted classes and that error is completely lost when the exception is thrown. `sigh`

**Comment by jsampson** [comment]
Glad to hear it! Thanks for sharing the details of your investigation.

**Comment by klauswuestefeld** [comment]
Wow. They simply NOPed allowArraySyntax instead of issuing a warning. :(

**Comment by jsampson** [comment]
Huh, good to know. I just checked our own `ObjectInputStreamWithClassLoader` to be sure, and it is already using `Class.forName` rather than `ClassLoader.loadClass`, so this should only bite codebases with their own custom class loading such as the one Dale is working on.

**Comment by jsampson** [comment]
Oh, apparently I actually took care of that myself in f50708f9bde69a504a0d4429dbf14e55b727a928 for Prevayler 2.4. From our release notes:

https://github.com/prevayler/prevayler/blob/5be1ca414f28471204459d05b42f49f8f9977cdd/CHANGES.txt#L136-L142

The linked JDK bug contains some good explanation for why it wasn't working.
